name: "release the project"
version: '1.0'

includes:
  - url: https://raw.githubusercontent.com/nehemming/cirocket-config/master/build/stdbuild.yml

params:

  # - name: projectName
  #   value: cirocket
  # - name: description
  #   value: '<<DESCRIPTION>>'
  # - name: builtBy
  #   value: '<<BUILDER>>'
  # - name: repoUser
  #   value: '<<USER>>'
  # - name: license
  #   value: 'Apache 2.0'

  - name: projectName
    value: '{{- or .projectName .Env.CIRCLE_PROJECT_REPONAME "cirocket"}}'
    print: true

  - name: description
    value: 'Rocket powered task runner to assist delivering ci build missions'
  - name: builtBy
    value: '{{- or .builtBy .Runtime.UserName }}'
    print: true
  - name: repoUser
    value: '{{- or .repoUser .Env.CIRCLE_PROJECT_USERNAME "nehemming"}}'
    print: true
  - name: license
    value: 'Apache 2.0'
  - name: includePackages
    value: yes
  - name: includeDocker
    value: yes
  - name: includeGHCR
    value: yes
  - name: includeBrews
    value: yes

  # config for the header and footer
  - name: resDir
    value: build
  - name: dockerfile
    value: '{{ .resDir }}/Dockerfile.release'
  - name: releaseHeader
    optional: true
    skipExpand: true
    path: '{{ .resDir }}/header.tplt'
  - name: releaseFooter
    optional: true
    skipExpand: true
    path: '{{ .resDir }}/footer.tplt'